shamefullyHoist: true
strictPeerDependencies: false

packages:
  - .

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
  - workerd

overrides:
  picomatch: ^4.0.3
