shamefullyHoist: true
strictPeerDependencies: false

packages:
  - .

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  sharp: false
  unrs-resolver: false
  vue-demi: false
  workerd: false
