shamefullyHoist: true
strictPeerDependencies: false

packages:
  - .

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - unrs-resolver
  - workerd

overrides:
  picomatch: ^4.0.3
  eslint: 9.38.0
