shamefullyHoist: true
strictPeerDependencies: false

packages:
  - .

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  sharp: false
  unrs-resolver: false
  vue-demi: false
  workerd: false

minimumReleaseAgeExclude:
  - '@nuxt/icon@2.5.0'
  - '@nuxtjs/mdc@0.23.1'
  - miniflare@5.20260804.0-alpha
  - nuxt-email-renderer@2.11.0
  - wrangler@4.120.1
