
name: "🚀 Feature request"
description: Suggest an idea or improvement for the project
labels: ["enhancement"]
assignees: Yizack

body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to fill out this feature request!
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what you would like to see.
      placeholder: Feature description
    validations:
      required: true
  - type: checkboxes
    id: additional
    attributes:
      label: Additional information
      description: Additional information that helps us decide how to proceed.
      options:
        - label: Would you be willing to help implement this feature?
