name = "mappedlove-images"
main = "index.ts"
compatibility_date = "2025-03-03"
compatibility_flags = ["nodejs_compat"]

[images]
binding = "IMAGES"

routes = [
  { pattern = "cdn.mappedlove.com/thumbnails", zone_name = "mappedlove.com" }
]
