name: autofix.ci
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v2
        with:
          runtime: node@lts
          cache: true

      - name: 🔎 Lint (code)
        run: node --run lint:fix

      - name: ⚙️ Auto-fix
        uses: autofix-ci/action@7a166d7532b277f34e16238930461bf77f9d7ed8
